### 获取课程信息
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}


### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes
Content-Type: application/json


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice": 100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "fdsf",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "tagstagstags",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级"
}


### 课程查询
GET {{content_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3NTA4NTE1MDUsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjhkNDEyYTExLTM1NjktNDllZS05Mzk0LTczODE0ZDliY2U0MyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.WYKNNwGB8MtmxcB8GVx6U4p1zQmg_0V5lFIDi8Jht9g


### 课程修改
PUT {{content_host}}/content/course/40
Content-Type: application/json


### 课程计划查询
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-type: application/json


### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="Snipaste_2025-01-21_10-59-20.png"
Content-Type: application/octet-stream

< C:/Users/94991/Pictures/Screenshots/Snipaste_2025-01-21_10-59-20.png


### 通过网关访问课程查询
GET {{gateway_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3NTEwMTg3ODYsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImU3OWEyMmVmLTRhNmQtNDYyMy1hOTMyLTViODlmMzRmMGU0MSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.PkqeIkY91My-j5-smQI5pe9C6EhCN4pLNvXWZ4mfTfo